# Generated by Django 3.1.6 on 2021-02-06 20:11

from django.db import migrations, models
import stocks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50000)),
                ('data_series', models.CharField(blank=True, choices=[(stocks.models.DataSeries['REAL_GDP'], 'real GDP'), (stocks.models.DataSeries['NOMINAL_GDP_CONVERTED'], 'nominal GDP converted from real GDP'), (stocks.models.DataSeries['NOMINAL_GDP_RAW'], 'nominal GDP')], max_length=200)),
                ('parameter_set', models.CharField(blank=True, choices=[(stocks.models.ParameterSets['TRADITIONAL'], 'Traditional'), (stocks.models.ParameterSets['NOVEL'], 'Novel'), (stocks.models.ParameterSets['UNORTHODOX'], 'Unorthodox')], max_length=200)),
            ],
        ),
    ]
