# Generated by Django 3.1.6 on 2021-02-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
    ]
