# Generated by Django 3.1.6 on 2021-02-06 20:12

from django.db import migrations
from stocks.models import *
import pickle

def initial_pickle(apps, schema_editor):
    pkl = "../../Predictions.pkl"
    data_series = [DataSeries.REAL_GDP, DataSeries.NOMINAL_GDP_CONVERTED, DataSeries.NOMINAL_GDP_RAW]
    workplace = [ParameterSets.TRADITIONAL, ParameterSets.NOVEL, ParameterSets.UNORTHODOX]
    temp = GraphData.objects.create(data=pkl, data_series=data_series[0], parameter_set=workplace[0])


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210206_1548'),
    ]

    operations = [
        migrations.RunPython(initial_pickle),
    ]

